name: "Setup Node.js development environment"
description: "Setup Node.js development environment for GitHub Actions"

runs:
  using: composite
  steps:
    - name: Setup | mise
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

    - name: Setup | pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      with:
        cache: true
