name: "Setup Node.js development environment"
description: "Setup Node.js development environment for GitHub Actions"

runs:
  using: composite
  steps:
    - name: Setup | mise
      uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0

    - name: Setup | pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      with:
        cache: true
