name: "Setup Node.js development environment"
description: "Setup Node.js development environment for GitHub Actions"

runs:
  using: composite
  steps:
    - name: Setup | mise
      uses: jdx/mise-action@c53b9236f0b3370f31520f8b142f141256d839c6 # v3.6.0

    - name: Setup | pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        cache: true
