allowBuilds:
  better-sqlite3: true
  core-js-pure: true
  dtrace-provider: true
  esbuild: true
  protobufjs: true
  re2: true
  unrs-resolver: true

minimumReleaseAge: 1440

saveExact: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - "@yarnpkg/libzip@3.2.2"
  - semver@5.7.2
  - semver@6.3.1
