minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@shun-shobon/style-guide"

onlyBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - esbuild
  - protobufjs
  - re2
  - unrs-resolver

saveExact: true

trustPolicy: no-downgrade
