# This workflow is managed by gh actions-lock.

name: ci
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup | Development environment
        uses: $/.github/actions/setup

      - name: Run | Lint
        run: pnpm run lint

  format:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup | Development environment
        uses: $/.github/actions/setup

      - name: Run | Format
        run: pnpm run format:check

  test:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup | Development environment
        uses: $/.github/actions/setup

      - name: Run | Test
        run: |
          pnpm exec renovate \
            --dry-run \
            --schedule= \
            --require-config=ignored \
            '${{ github.repository }}'
        env:
          RENOVATE_USERNAME: renovate[bot]
          RENOVATE_GIT_AUTHOR: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
          RENOVATE_TOKEN: ${{ github.token }}
          RENOVATE_BASE_BRANCHES: ${{ github.sha }}
          RENOVATE_CONFIG_FILE: ./renovate.json
          LOG_LEVEL: debug

  status-check:
    needs: [lint, format, test]
    if: ${{ always() }}
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - name: Verify | All CI jobs succeeded
        env:
          RESULTS: ${{ toJSON(needs.*.result) }}
        run: jq -e 'all(.[]; . == "success")' <<< "$RESULTS"
